server:
  port: ${GATEWAY_SERVICE_PORT:8080}

spring:
  main:
    web-application-type: reactive
  jmx:
    enabled: false
  security:
    user:
      name: ${GATEWAY_SERVICE_SECURITY_USER_NAME:gateway}
      # password: ${GATEWAY_SERVICE_SECURITY_USER_PASSWORD:12345678}
      password: ${GATEWAY_SERVICE_SECURITY_USER_PASSWORD:{bcrypt}$2a$10$qlHeFzwx3MybjEEFfZgEaOZCwOZ1.HLSr93PWFjmiFA7GIz/pV2ZC}
  cloud:
    cloud:
      circuitbreaker:
        resilience4j:
          enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # ===================================== [SPRING ADMIN]
        - id: spring-admin-service
          uri: ${SPRING_ADMIN_SERVICE_URI:http://localhost:8762}
          predicates:
            - Path=${SPRING_ADMIN_SERVICE_CONTEXT_PATH:/}**
            - Header=Authorization, \d+
          filters:
            - RewritePath=/admin(?<segment>/?.*), $\{segment}
            - AddRequestHeader=X-Client,web
            - AddResponseHeader=X-Type,inorganic
            - name: CircuitBreaker
              args:
                name: springAdminService
                fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 5
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
        # ===================================== [DISCOVERY]
        - id: discovery-service
          uri: ${DISCOVERY_SERVICE_URI:http://localhost:8761}
          predicates:
            - Path=${DISCOVERY_SERVICE_CONTEXT_PATH:/}**
            - Header=Authorization, \d+
          filters:
            - RewritePath=/discovery(?<segment>/?.*), $\{segment}

resilience4j:
  circuitbreaker:
    configs:
      shared:
        slidingWindowSize: 10                     # unit request
        permittedNumberOfCallsInHalfOpenState: 5  # unit request
        failureRateThreshold: 50                  # percent
        waitDurationInOpenState: 10000            # 10 seconds
        registerHealthIndicator: true
    instances:
      springAdminService:
        base-config: shared
  timelimiter:
    instances:
      springAdminService:
        timeoutDuration: 2s
  retry:
    configs:
      default:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 5s
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
